#include "stdafx.h"

#ifndef PUBLICMACROHEADER_H
#define PUBLICMACROHEADER_H

#define MESSAGE_LEFTLIST_VSCROLL	(WM_USER+1010)
#define DLGMSG_EXTRADLG_CLOSE		(WM_USER+150)

#define WM_TAB_SELECTED  WM_USER+111

#define WM_PANELVIEW_BTN_CLICK  WM_USER+112
#define WM_PANELVIEW_BTN_DBCLICK  WM_USER+113

//#define COLDLG_TIMER_CLEAN_TEXTOUT  1010


#define CONFIG_SHEET_RESTART_ADJUST_PANELORDER   100
#define CONFIG_SHEET_LOAD_IN   101
#endif // PUBLICMACROHEADER_H
