#if !defined(AFX_PGCELL_H__08CCAF53_23A4_444C_BD53_A35686691540__INCLUDED_)
#define AFX_PGCELL_H__08CCAF53_23A4_444C_BD53_A35686691540__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPgCell wrapper class

class CPgCell : public CWnd
{
protected:
	DECLARE_DYNCREATE(CPgCell)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xfaaff854, 0xb2b9, 0x4f7c, { 0x8d, 0xc6, 0xfa, 0x39, 0xf0, 0x9, 0xa9, 0x46 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	unsigned long GetFixedCellBackColor();
	void SetFixedCellBackColor(unsigned long);
	unsigned long GetPgCellBackColor();
	void SetPgCellBackColor(unsigned long);
	unsigned long GetSetPGOCXBKColor();
	void SetSetPGOCXBKColor(unsigned long);
	unsigned long GetTableSheetColor();
	void SetTableSheetColor(unsigned long);
	short GetPgCellStyle();
	void SetPgCellStyle(short);
	unsigned long GetFocusCellBKColor();
	void SetFocusCellBKColor(unsigned long);

// Operations
public:
	void SetRowCount(short nRows);
	void SetColCount(short nCols);
	void ShowPgCell(short nWhichPg, long bShow);
	void AddPages(LPCTSTR strLabel, short nPages);
	void DeletePages(short nIndex, short nCount);
	void InsertPages(LPCTSTR strLabel, short nLocation, short nCount);
	short GetCurrentPage();
	void SetCurrentPage(short nCurPage, long bShow);
	short GetTotalPages();
	void ResetContent();
	BOOL SetPageLabel(short nWhichPage, LPCTSTR lpsPageLabel);
	BOOL GetPageLabel(short nWhichPage, BSTR* lpsPageLabel);
	BOOL SetFixedRowCount(short nFixedRows);
	BOOL SetFixedColCount(short nFixedCols);
	BOOL SetTextBkColor(unsigned long clrTextBkColor);
	BOOL SetItemText(short nRow, short nCol, LPCTSTR lpcsItemText);
	BOOL GetItemText(short nRow, short nCol, VARIANT* pvarItemText);
	short GetRowCount();
	short GetColCount();
	BOOL SetItemState(short nRow, short nCol, double dwState);
	BOOL MergeCells(short nStartRow, short nStartCol, short nEndRow, short nEndCol);
	BOOL UnMergeCells(short nStartRow, short nStartCol, short nEndRow, short nEndCol);
	BOOL SetRowHeight(short nRow, short nHeight);
	BOOL SetColWidth(short nCol, short nWidth);
	BOOL SetFixedBkColor(unsigned long clrFixedBkColor);
	BOOL SetFixedTextColor(unsigned long clrFixedTextColor);
	LPDISPATCH GetFont();
	BOOL SetGridBkColor(unsigned long clrGridBkColor);
	BOOL SetGridColor(unsigned long clrGridColor);
	BOOL SetGridLineColor(unsigned long clrGridLineColor);
	BOOL SetCellType(short nRow, short nCol, long unCellType);
	BOOL SetItemTextFmt(short nRow, short nCol, long unFmt);
	BOOL SetTextColor(unsigned long clrTextColor);
	BOOL AutoSize();
	BOOL DeleteRow(short nRow);
	BOOL Print();
	BOOL PrintPreview();
	long GetCellDC(short nRow, short nCol);
	BOOL InsertRow(LPCTSTR strRowHeading, short nInsertRowPos);
	BOOL InsertCol(LPCTSTR strColHeading, short nInsertColPos);
	BOOL DeleteCol(short nCol);
	BOOL SetCurrDrawModelCell(short nRow, short nCol);
	BOOL LineTo(short nStartPosX, short nStartPosY, short nEndPosX, short nEndPosY);
	BOOL SetLineStyle(long unStyle, short nLineWidth, unsigned long clrColor);
	BOOL Circle(short nCirclePointX, short nCirclePointY, short nCircleRadius);
	BOOL AddComboCellItem(short nRow, short nCol, LPCTSTR strItem);
	BOOL SetCellFont(short nRow, short nCol, long nHeight, long nWidth, long lnStyle, LPCTSTR strFontName);
	BOOL SetItemBkColour(short nRow, short nCol, unsigned long clrBkColor);
	BOOL SetPageTableColor(unsigned long nColor);
	BOOL SetComboCellCurSel(short nRow, short nCol, short nCurSel);
	short GetComboCellCurSel(short nRow, short nCol);
	short GetColWidth(short nCol);
	short GetRowHeight(short nRow);
	BOOL DrawText(short nDarwPosX, short nDarwPosY, LPCTSTR strText, short nTextAlign);
	BOOL LineToHook(short nStartPosX, short nStartPosY, short nEndPosX, short nEndPosY, short nFlag, short nPara);
	BOOL SetCellFillRect();
	BOOL SetDrawTextFontStyle(short nHeight, short nWidth, short nWeight, LPCTSTR strFontName, unsigned long clrText);
	BOOL SetDrawTextFontStyleDef(short nHeight, short nWidth, short nWeight);
	BOOL Save();
	BOOL Load();
	BOOL SetCellRowFillRect(short nCol);
	BOOL ArcToHook(short nStartPointX, short nStartPointY, short nEndPointX, short nEndPointY, short nAngle, short nDirection, short nFlag);
	BOOL Arc(short nStartPointX, short nStartPointY, short nEndPointX, short nEndPointY, short nAngle, short nDirection);
	BOOL SetArcHookStyle(short nArcRadius, short nArcExtendLen);
	BOOL SetHookStyle(short nArcRadius, short nArcExtendLen);
	BOOL SetCellColFillRect(short nRow);
	BOOL Polygon(short nCircleX, short nCircleY, short nRadius, short nBorders, short nFlag);
	BOOL PolygonToHook(short nCircleX, short nCircleY, short nRadius, short nBorders, short nStartAngle, short nHookFlag, float nMark);
	BOOL DrawRectangle(short nStartPosX, short nStartPosY, short nEndPosX, short nEndPosY);
	BOOL ShowModifySteelDlg();
	BOOL ShowSelfDrawDlg(short Row, short Col);
	BOOL SetVectorModel(BOOL bVectorModel);
	BOOL EnableCellCrossLine(short nStartRow, short nStartCol, short nEndRow, short nEndCol, BOOL bEnable);
	BOOL DescribeGraph(long nGraphNum, long nDataFlag, long nDataSum, double* adGraphInfo);
	short GetHookArcRadius(short nRow, short nCol);
	BOOL SetCellReadOnly(short nRow, short nCol, BOOL bReadOnly);
	BOOL AppendRow(short nRows);
	BOOL AppendCol(short nCols);
	BOOL GetSteelInfo(short nRow, short nCol, long* nSteelNO, short* nValueCount, BSTR* aStrData);
	BOOL SetSteelInfo(short nRow, short nCol, long lSteelNO, short nTextValueNO, LPCTSTR strData);
	BOOL EnableTitleTips(long bTitleTips);
	double GetCellData(short nRow, short nCol);
	BOOL SetCellValue(short nRow, short nCol, double dvalue, short ndigit);
	BOOL ReadSteelDataBase(LPCTSTR strSteelDataAddress);
	BOOL SetCellSteelGraph(short Row, short Col, long nSteelNO, short nValueCount, double* pDValueData, short ndigit);
	BOOL SetReadOnly(BOOL bReadOnly);
	long GetAllGraphDataAddress(short* pGraphDataCount);
	BOOL SetAllGraphDataAddress(long pDataAddress, short nGraphDataCount);
	long BuildSearchSteelGraphData(short nSortClass, short nfoldCount, short nHooKCount, short nPara);
	BOOL SetCellSearchSteelGraph(short Row, short Col, short nNO);
	long DoGetCurrentRow();
	long DoGetCurrentCol();
	BOOL DeleteRows(short Row, short Count);
	BOOL DeleteCols(short Col, short Count);
	BOOL SetPrintTitle(LPCTSTR strPrintHeader);
	BOOL SetCellCheckVal(short nRow, short nCol, BOOL bVal);
	BOOL GetCellCheckVal(short nRow, short nCol);
	BOOL SetCellTypeA(short nRow, short nCol, long unCellType, long lStyle);
	BOOL SetCellMoveDirection(short nMovDirection, BOOL bNewLineDirection);
	BOOL RemoveAllComboCellItem(short nRow, short nCol);
	CString GetCellString(short nRow, short nCol);
	CString GetPageLabelText(short nPageIndex);
	BOOL SetCellBatchModifiable(BOOL bBatchModifiable);
	BOOL AddTreeCell(short nRow, short nCol, short* TreeData, short nAmount, long lStyle);
	BOOL ShowTabSheet(BOOL bShowTabSheet);
	BOOL SetCellFocus(short nRow, short nCol);
	BOOL GetCellFocus(short* pnRow, short* pnCol);
	void SetCellFocusBKColor(unsigned long clrFocusCellBKClr);
	unsigned long GetCellFocusBKColor();
	void RefreshCell();
	unsigned long GetItemBkColour(short nRow, short nCol);
	BOOL SetGridRowHeight(short nGridRowHeight);
	BOOL SetGridColWidth(short nGridColWidth);
	CString GetVersion();
	BOOL SetCellMoveDirectionA(short nMovDirection, short nNewLineDirection);
	long BondTreeCtrl(long pTreeCtrl, short nStyle, LPCTSTR strRootName);
	BOOL Clear();
	void SetDefRowHeight(short nDefRowHeight);
	void SetDefColWidth(short nDefColWidth);
	void SetRowSizingMode(BOOL bRowSizingMode);
	BOOL AutoSizeColumn(short nCol);
	BOOL AutoSizeRow(short nRow);
	void AutoSizeColumns();
	void AutoSizeRows();
	void SetRowHeightMin(short nRowHeightMin);
	long GetRowHeightMin();
	void SetColumnReadOnly(short nColumn, BOOL bReadOnly);
	void SetRowReadOnly(short nRow, BOOL bReadOnly);
	long GetTopVisibleRow();
	BOOL SetCellFontFmt(short nRow, short nCol, short nFontSize, short nFontWeight, LPCTSTR strFontName, unsigned long clrFontColor);
	BOOL SetTopVisibleRow(short nRow);
	void DisEditCell(BOOL bDisableEditCell);
	void GetSelectedCellRange(short* pMinRow, short* pMinCol, short* pMaxRow, short* pMaxCol);
	void ClearContent();
	void SetGridTextAlign(short nAlign);
	void SetColTextAlign(short nCol, short nAlign);
	long BondTreeCtrlNew(long pTreeCtrl, short nStyle, LPCTSTR strRootName, short nRow, short nCol);
	void SetCellDATE(short nRow, short nCol, short nYear, short nMonth, short nDay);
	void GetCellDATE(short nRow, short nCol, short* nYear, short* nMonth, short* nDay);
	BOOL EnableVKDELETE(BOOL bEnableVKDELETE);
	long GetSelectedCellMap(long* pCount, long* pSelectedCellRowData, long* pSelectedCellColData);
	void PrintToVBhdc(long hdc, long left, long top, long right, long bottom, long nStartRow, long nStartCol, long nEndRow, long nEndCol, float PFDXS, long optional);
	void SetPageTableBKColor(unsigned long clrTabSheetBKColor);
	BOOL ClearDrawCellData(short nRow, short nCol);
	BOOL SetCellPicture(short nRow, short nCol, LPCTSTR strSourcePicture, long nFlag);
	BOOL SetCellImage(short nRow, short nCol, long pImageList, long nImageIndex, long nFlag);
	BOOL SetItemTextColour(short nRow, short nCol, unsigned long clrTextColor);
	BOOL GetCellRect(short nRow, short nCol, long* lpRect);
	long GetCellWindow();
	BOOL SetHeaderSort(long nByVal, BOOL bSortItem);
	BOOL SetEnableMOUSESELECTCOL(BOOL bEnableMOUSESELECTCOL);
	short GetFixedColCount();
	short GetFixedRowCount();
	BOOL EnableGrid(BOOL bEnableGrid);
	BOOL SetWindowRect(long left, long top, long right, long bottom);
	BOOL SetDefaultCellFont(LPDISPATCH lpDefaultCellFont);
	BOOL SetDefaultCellFontA(LPCTSTR strFontName, long lSize, BOOL bQuality, BOOL bItalic, BOOL bStrikeOut, BOOL bUnderline);
	void SetCellFocusForeColor(unsigned long clrCellFocusForeColor);
	void SetSelectedCellRangeBKColor(unsigned long clrSelectedCellRangeBKColor);
	void SetSelectedCellRangeTextColor(unsigned long clrSelectedCellRangeTextColor);
	void SetSelectedCellRangeForeColor(unsigned long clrSelectedCellRangeForeColor);
	void SetEditCellStyle(BOOL bAutoSize, BOOL bIsBorder, long lFlag);
	void PrintPreviewA();
	long GetCellWindowA();
	long GetCellFont(short nRow, short nCol, long* lSize, long* lWidth, long* lHeight, long* lWeight, BSTR* pstrFontName);
	BOOL GetCellVirtualRect(short nRow, short nCol, long* lpRect);
	BOOL DoSetPrintHead(LPCTSTR strLeft, LPCTSTR strMid, LPCTSTR strRight);
	BOOL DoSetPrintFoot(LPCTSTR strLeft, LPCTSTR strMid, LPCTSTR strRight);
	BOOL DoExportExcelFile(LPCTSTR strExcelFileName, BOOL bOpenExcel);
	BOOL SetDrawTextCanPickUp(short nRow, short nCol, BOOL bCanPickUpDrawText);
	void DoSetPrintMargin(short top, short bottom, short left, short right);
	void DoSetPrintLabel(BOOL collabel, BOOL rowlabel);
	void DoSetPrintHeadLine(BOOL bPrintHeadLine);
	void DoSetPrintFootLine(BOOL bPrintFootLine);
	void DoSetPrintPaperMode(BOOL bHOrientation);
	BOOL CopyRow(short nsouRow, short ndesRow, BOOL bIncFixedCol);
	BOOL CopyCol(short nSouCol, short nDesCol, BOOL bIncFixedRow);
	BOOL SetCellPictureHandle(short nRow, short nCol, long unSourceHandle, long nStyle, long nAlign);
	BOOL SetRowCountA(long lRow);
	long GetCellType(short nRow, short nCol);
	void SetBatchFlag(BOOL bBatch);
	BOOL DrawTextR(short nDarwPosX, short nDarwPosY, LPCTSTR strVariableName, LPCTSTR strDrawText, short nTextAlign, short nAngle);
	BOOL SetDrawTextR(long lRow, long lCol, LPCTSTR strVariableName, LPCTSTR strNewDrawText);
	BOOL EnableSelection(BOOL bEnableSelection);
	BOOL SetDefTextFormat(long unFmt);
	BOOL SetDrawBtnText(long nRow, long nCol, short nIndex, LPCTSTR strBtnText);
	BOOL SetRowVisible(long nRow, BOOL bVisible);
	BOOL SetColVisible(long nCol, BOOL bVisible);
	BOOL SetGridColResize(BOOL bGridColResize);
	BOOL SetGridRowResize(BOOL bGridRowResize);
	BOOL GetCellEditingState(long lRow, long lCol);
	BOOL SetGridEndEditing();
	BOOL EnableScrollBars(long nBar, BOOL bEnable);
	void ShowErrorTip(BOOL bShowErrorTip);
	CString GetComboCellItem(long nRow, long nCol, long nIndex);
	long GetComboCellItemCount(long nRow, long nCol);
	BOOL EnableCellCheck(long nRow, long nCol, BOOL bEnableCheck);
	void ShowPrinterBorder(BOOL bShowPrinterBorder);
	BOOL SetCellEditingState(long lRow, long lCol, BOOL bEditing);
	BOOL IsShowPrinterBorder();
	BOOL SetComboCellItem(long lRow, long lCol, short nIndex, LPCTSTR strItem);
	long DelComboCellItem(long lRow, long lCol, short nIndex);
	void DoSetPrintFitToPage(BOOL bFitToPage);
	BOOL GetRowVisible(long nRow);
	BOOL GetColVisible(long nCol);
	BOOL GetCellReadOnly(long nRow, long nCol);
	void SetStlEditAttrib(long nRow, long nCol, long wAttrib);
	long GetStlEditAttrib(long nRow, long nCol);
	void SetStlEditDefaultGrade(long nRow, long nCol, long nGrade);
	long GetStlEditDefaultGrade(long nRow, long nCol);
	void SetStlEditType(long nRow, long nCol, long wType);
	long GetStlEditType(long nRow, long nCol);
	void SetStlEditFlag(long nRow, long nCol, long wFlag, BOOL bValue);
	BOOL GetStlEditFlag(long nRow, long nCol, long wFlag);
	void EnableCellResize(BOOL bCellResize);
	long GetPagesCount();
	void DeleteAllPages();
	void SetBatchFlagA(BOOL bBatch, long nInitCount, long nIncrement);
	long GetRowCountA();
	void EnableGridCrossLine(long lFlag);
	BOOL SetItemTextA(long nRow, long nCol, LPCTSTR ItemText);
	CString GetCellStringA(long nRow, long nCol);
	BOOL SetCellString(long nRow, long nCol, LPCTSTR strCellString);
	BOOL SetItemTextFmtA(long nRow, long nCol, long unFmt);
	BOOL GetItemTextA(long nRow, long nCol, VARIANT* pvarItemText);
	void DrawCellHLine(long nRow, long nCol, BOOL bTop, long lLineStyle, long lLineSize, unsigned long clrLineColor);
	void DrawCellVLine(long nRow, long nCol, BOOL bLeft, long lLineStyle, long lLineSize, unsigned long clrLineColor);
	void DrawCellXLine(long nRow, long nCol, BOOL bLeftTop, long lLineStyle, long lLineSize, unsigned long clrLineColor);
	void ClearDrawCellLineData(long nRow, long nCol);
	BOOL SetItemBkColourA(long nRow, long nCol, unsigned long clrBkColor);
	BOOL SetItemTextColourA(long nRow, long nCol, unsigned long clrTextColor);
	BOOL InsertRowA(LPCTSTR strRowHeading, long nInsertRowPos);
	BOOL SetRowHeightA(long nRow, long nHeight);
	BOOL SetComboCellCurSelA(long nRow, long nCol, long nCurSel);
	BOOL SetCellTypeB(long nRow, long nCol, long unCellType, long lStyle);
	BOOL SetCurrDrawModelCellA(long nRow, long nCol);
	BOOL SetDrawTextCanPickUpA(long nRow, long nCol, BOOL bCanPickUpDrawText);
	BOOL DeleteRowA(long nRow);
	BOOL DeleteRowsA(long nStartRow, long Count);
	BOOL SetCellFocusA(long nRow, long nCol);
	BOOL AddComboCellItemA(long nRow, long nCol, LPCTSTR strItem);
	BOOL SetCellReadOnlyA(long nRow, long nCol, BOOL bReadOnly);
	BOOL MergeCellsA(long nStartRow, long nStartCol, long nEndRow, long nEndCol);
	BOOL UnMergeCellsA(long nStartRow, long nStartCol, long nEndRow, long nEndCol);
	BOOL SetCellFontA(long nRow, long nCol, long nHeight, long nWidth, long lnStyle, LPCTSTR strFontName);
	BOOL SetCellFontFmtA(long nRow, long nCol, long nFontSize, long nFontWeight, LPCTSTR strFontName, unsigned long clrFontColor);
	BOOL DoExportExcelFileA(LPCTSTR strExcelFileName, BOOL bOpenExcel, BOOL bFormat);
	BOOL SetCellCheckValA(long nRow, long nCol, long nVal);
	long GetCellCheckValA(long nRow, long nCol);
	BOOL SetDefaultCellTextColor(unsigned long clrDefTextColor);
	BOOL SetCellTip(LPCTSTR strTip);
	CString GetDrawTextR(long nRow, long nCol, LPCTSTR strVariableName);
	BOOL DoGetPrintPaperMode();
	BOOL DoGetPrintMargin(long* top, long* bottom, long* left, long* right);
	BOOL DoGetPrintFitToPage();
	BOOL DoGetPrintHeadLine();
	BOOL DoGetPrintFootLine();
	void DoGetPrintHead(BSTR* strLeft, BSTR* strMid, BSTR* strRight);
	void DoGetPrintFoot(BSTR* strLeft, BSTR* strMid, BSTR* strRight);
	BOOL DoGetPrintGridFont(long* plffont);
	BOOL DoSetPrintGridFont(long* plffont);
	BOOL DoSetPrintFixedRowFont(long* plffont);
	BOOL DoGetPrintFixedRowFont(long* plffont);
	BOOL DoSetPrintTitleFont(long* plffontLeft, long* plffontMid, long* plffontRight);
	BOOL DoGetPrintTitleFont(long* plffontLeft, long* plffontMid, long* plffontRight);
	BOOL DoSetPrintGridBKClr(unsigned long clrGridBK);
	unsigned long DoGetPrintGridBKClr();
	unsigned long DoGetPrintFixedRowBKClr();
	BOOL DoSetPrintFixedRowBKClr(unsigned long clrFixedRowBK);
	BOOL DoSetPrintShowFixedRow(BOOL bShowFixedRow);
	BOOL DoGetPrintShowFixedRow();
	BOOL DoSetPrintShowFixedCol(BOOL bShowFixedCol);
	BOOL DoGetPrintShowFixedCol();
	BOOL DoSetPrintShowGridCrossLine(long nShowGridCrossLine);
	long DoGetPrintShowGridCrossLine();
	BOOL DoGetPrint3D();
	BOOL DoSetPrint3D(BOOL b3D);
	BOOL DoGetPrintSingleColor();
	BOOL DoSetPrintSingleColor(BOOL bSingleColor);
	BOOL DoSetPrintShowBKClr(BOOL bShowBKClr);
	BOOL DoGetPrintShowBKClr();
	BOOL SetCellValueA(long nRow, long nCol, double dvalue, short ndigit);
	BOOL SetCellPictureA(long nRow, long nCol, LPCTSTR strSourcePicture, long nFlag);
	void SetTabHSBarPercent(double dHSBarPercent);
	LPDISPATCH GetTreeCellCtrl();
	LPDISPATCH ExportTreeItemClass();
	BOOL AddComboCellItemPic(long nRow, long nCol, LPCTSTR PicPath);
	long GetSelectedCellMapEx(long* pIndex, long* pSelRow, long* pSelCol);
	BOOL EnableClipboardCtrlV(BOOL bEnableClipboardCtrlV);
	BOOL SetSingleRowSelection(BOOL bSinRowSele);
	BOOL EnableClipboardCtrlC(BOOL bEnableClipboardCtrlC);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PGCELL_H__08CCAF53_23A4_444C_BD53_A35686691540__INCLUDED_)
